### ISSUE TITLE
when batch size 1 it crashes without any error messages

### ISSUE THREAD

**Issue by miltosc** [EmptySamurai/pytorch-reconet#2]
Hello!
First of all congratulations for your nice project.

I downloaded all the training material and now trying to train with a style image. With batch size 2 it complains about cuda memory although i have 8 GB memory in my graphics card.

So i put batch size 1 in your code at train.py. After few seconds it gives me prompt without any error message.

I run it on windows using cuda 10.2 and latest cudnn.

Does it need cuda 9?

Please help.
Thanks in advance

**Comment by EmptySamurai** [comment]
Hello.
Unfortunately at the moment I don't have a server with GPU at my disposal.

Have you tried to debug and understand what is the last line it executes successfully? And does program exit with 0 exit code or something different?

P.S. Such silent termination is usually a sign of some problem with cuda/cudnn/drivers. If I remember correctly, I trained it using single 1080 Ti with 12Gb of memory, cuda 10.1 on Ubuntu server.

**Comment by miltosc** [comment]
I managed to make it work in linux that happens only in windows
