### ISSUE TITLE
Reconet network preprocessing

### ISSUE THREAD

**Issue by virgile-blg** [EmptySamurai/pytorch-reconet#3]
Hi, and thanks for sharing your work.

Can you explain why you need to scale RecoNet input images through the ` preprocess_for_reconet` function ?

Isn't the network fully trained from scratch ?

Thanks !

**Comment by EmptySamurai** [comment]
Network is indeed fully trained from scratch. `preprocess_for_reconet` is just a function that transforms image from [0, 1] to [-1, 1] range. There are two reasons I used it:

1. `tanh` activation at last layer produces outputs in [-1; 1] range. It's much more convenient to work with the same scale at inputs and outputs
2. Centring input data around 0 can give a little boost to output performance sometimes. Though, to be fair, I didn't perform ablation study

**Comment by virgile-blg** [comment]
Ok, thanks a lot for answering. One other option would be to replace `tanh` activation by a `sigmoid` one, though that's not following the original paper.
